#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export MONO_GAC_PREFIX="/usr/local"
export PATH=$PATH:~/bin

alias pwdcopy='pwd | tr -d "\r\n" | pbcopy'
alias yoink='open -a Yoink'
alias brackets='open -a Brackets'
